# Generated by Django 2.2.3 on 2019-11-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191111_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
