# Generated by Django 2.2.3 on 2019-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191111_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
