# Generated by Django 2.2.3 on 2019-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_advertisement_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='location',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
