# Generated by Django 2.2.3 on 2019-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191114_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
